//
//  DeviceTableViewCell.h
//  BlueSTSDKExample
//
//  Created by Giovanni Visentini on 03/08/15.
//  Copyright (c) 2015 STCentralLab. All rights reserved.
//

#import <UIKit/UIKit.h>

/**
 *  simple class used for show the device information in the device table
 */
@interface DeviceTableViewCell : UITableViewCell

/**
 *  board image
 */
@property (strong, nonatomic) IBOutlet UIImageView *boardImage;

/**
 *  device name
 */
@property (strong, nonatomic) IBOutlet UILabel *boardName;

/**
 * unique id used for identify the board inside the sdk. it can be the mac 
 * address or the uuid generated by the system
 */
@property (strong, nonatomic) IBOutlet UILabel *boardDetails;

@end
